name: gajimu
description: Build using Vibe Studio
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: '>=3.22.3'

dependencies:
  gap: ^3.0.1
  intl: ^0.19.0
  file_picker: ^8.1.2
  equatable: ^2.0.5  
  flutter:
    sdk: flutter
  stacked: ^3.4.2    
  stacked_services: ^1.4.0
  logger: ^1.4.0
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.3.0    
  sentry_flutter: ^8.12.0
  sentry_dart_plugin: ^2.4.1
  shared_preferences: ^2.5.3

dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^3.0.1  
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.8.0    
  mocktail: ^1.0.4
  stacked_generator: ^1.3.3  

flutter:
  uses-material-design: true
  generate: true

flutter_launcher_icons:
  android: "launcher_icon"

# sentry:
#   project: my_app-410d52
#   org: steve-jm
#   auth_token: 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
#   upload_source_maps: true
#   ignore_missing: true